FROM nginx:alpine

RUN echo '<html><body><h1>Hello from T2S. Congratulations for having set up a complete infrastructure that is scalable, highly available, resilient, accessible, 
and cost-efficient. Great job!</h1></body></html>' > /usr/share/nginx/html/index.html
